{{- range $index, $appset := .Values.appsets }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $appset.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ $.Values.repo.url }}
        revision: {{ $.Values.repo.revision }}
        directories:
          - path: {{ $appset.name }}/*
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ default `{{path.basename}}` $appset.namespace }}' # TODO Fix fo deploys with hardcoded namespaces .eg Longhorn? NeuVector? 
      project: default # TODO Project options
      source:
        repoURL: {{ $.Values.repo.url }}
        path: '{{ `{{path}}` }}'
        targetRevision: {{ $.Values.repo.revision }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
{{- end }}